### ISSUE TITLE
Notes about Challenge Mode

### ISSUE THREAD

**Issue by Lhwhatever** [rcywop21/wanderlust#58]
- Challenge Mode tab will be unlocked by either completing Shrine of the Innocent, Part 1 OR The Finches Code, Decoded.
- Explain the difficulty introduced by Challenge Mode (less Oxygen, pumps don't work).
- Edit message from end of Finches storyline to say that it gives more information about Challenge Mode.
- Show the Challenge Mode Oxygen multiplier when the `knowsCrimson` stat is active.
- Multiplier is calculated by `Math.floor(0.15, 0.125 + 0.025 * globalState.artefactsFound)`
- Show the time which Challenge Mode would be completed by.

Replaces #30, #41 and #52.

**Comment by WangZijun97** [comment]
Resolved by commit 54a8bdf
